#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.Tilemaps;

[InitializeOnLoad]
public static class SnowmanTerrainTilemapConverter
{
    private const string SceneName = "Adventure of A Snowman 2D";
    private const string ReferenceRootName = "Assignment04ReferenceObjects";
    private const string TopPlatformName = "Top Platform";
    private const string BottomPlatformName = "Bottom Platform";
    private const string GridName = "Terrain Tilemap Grid";
    private const string TerrainTilemapName = "Painted Terrain Tilemap";
    private const string DecorationTilemapName = "Painted Decoration Tilemap";
    private const string BackupName = "Terrain Sprite Sources (Disabled)";
    private const string TileFolder = "Assets/Tiles/AutoGeneratedTerrain";
    private const float CellSize = 0.25f;

    static SnowmanTerrainTilemapConverter()
    {
        EditorApplication.delayCall += TryAutoConvert;
        EditorSceneManager.sceneOpened += OnSceneOpened;
    }

    [MenuItem("Tools/Snowman/Convert Chunk Sprites To Tilemaps")]
    public static void ConvertOpenSceneFromMenu()
    {
        ConvertOpenScene(showDialog: true);
    }

    private static void TryAutoConvert()
    {
        if (EditorApplication.isPlayingOrWillChangePlaymode)
        {
            return;
        }

        ConvertOpenScene(showDialog: false);
    }

    private static void OnSceneOpened(Scene scene, OpenSceneMode mode)
    {
        if (scene.IsValid() && scene.name == SceneName)
        {
            EditorApplication.delayCall += TryAutoConvert;
        }
    }

    private static void ConvertOpenScene(bool showDialog)
    {
        if (EditorApplication.isPlayingOrWillChangePlaymode)
        {
            return;
        }

        Scene scene = SceneManager.GetActiveScene();
        if (!scene.IsValid() || scene.name != SceneName)
        {
            return;
        }

        GameObject referenceRoot = GameObject.Find(ReferenceRootName);
        if (referenceRoot == null)
        {
            return;
        }

        EnsureTileFolderExists();

        int terrainCount = 0;
        int decorationCount = 0;

        terrainCount += ConvertPlatformRoot(referenceRoot.transform.Find(TopPlatformName));
        terrainCount += ConvertPlatformRoot(referenceRoot.transform.Find(BottomPlatformName));

        if (terrainCount + decorationCount <= 0)
        {
            return;
        }

        AssetDatabase.SaveAssets();
        EditorSceneManager.MarkSceneDirty(scene);
        EditorSceneManager.SaveScene(scene);

        if (showDialog)
        {
            EditorUtility.DisplayDialog(
                "Chunk Tilemap Converter",
                "Converted the platform sprites into Tilemaps and moved the old sprites into disabled backup folders.",
                "OK");
        }
    }

    private static int ConvertPlatformRoot(Transform platformRoot)
    {
        if (platformRoot == null)
        {
            return 0;
        }

        Transform backupRoot = GetOrCreateBackupRoot(platformRoot);
        List<SpriteRenderer> sprites = FindChunkSprites(platformRoot, includeInactive: false);
        MergeMissingSprites(sprites, FindChunkSprites(backupRoot, includeInactive: true));

        if (sprites.Count == 0)
        {
            return 0;
        }

        Grid grid = GetOrCreateGrid(platformRoot);
        Tilemap terrainTilemap = GetOrCreateTilemap(grid.transform, TerrainTilemapName, true, 1);
        Tilemap decorationTilemap = GetOrCreateTilemap(grid.transform, DecorationTilemapName, false, 2);

        terrainTilemap.ClearAllTiles();
        decorationTilemap.ClearAllTiles();

        HashSet<Vector3Int> usedTerrainCells = new HashSet<Vector3Int>();
        HashSet<Vector3Int> usedDecorationCells = new HashSet<Vector3Int>();

        int converted = 0;
        for (int i = 0; i < sprites.Count; i++)
        {
            SpriteRenderer spriteRenderer = sprites[i];
            if (spriteRenderer == null || spriteRenderer.sprite == null)
            {
                continue;
            }

            if (!ShouldConvertSpriteRenderer(spriteRenderer))
            {
                continue;
            }

            bool isTerrain = IsSolidTerrainSpriteName(spriteRenderer.name);
            Tilemap targetTilemap = isTerrain ? terrainTilemap : decorationTilemap;
            HashSet<Vector3Int> usedCells = isTerrain ? usedTerrainCells : usedDecorationCells;
            Tile tile = GetOrCreateTile(spriteRenderer.sprite);

            Vector3Int cell = targetTilemap.WorldToCell(spriteRenderer.transform.position);
            cell = FindNearestEmptyCell(cell, usedCells);
            usedCells.Add(cell);

            targetTilemap.SetTile(cell, tile);
            spriteRenderer.gameObject.SetActive(false);
            spriteRenderer.enabled = false;
            spriteRenderer.transform.SetParent(backupRoot, true);
            converted++;
        }

        terrainTilemap.CompressBounds();
        decorationTilemap.CompressBounds();
        return converted;
    }

    private static List<SpriteRenderer> FindChunkSprites(Transform root, bool includeInactive)
    {
        List<SpriteRenderer> sprites = new List<SpriteRenderer>();
        if (root == null)
        {
            return sprites;
        }

        SpriteRenderer[] allSprites = root.GetComponentsInChildren<SpriteRenderer>(true);
        for (int i = 0; i < allSprites.Length; i++)
        {
            SpriteRenderer spriteRenderer = allSprites[i];
            if (spriteRenderer == null || spriteRenderer.sprite == null)
            {
                continue;
            }

            if (!includeInactive && (!spriteRenderer.gameObject.activeInHierarchy || !spriteRenderer.enabled))
            {
                continue;
            }

            if (IsInsideGeneratedTilemap(spriteRenderer.transform))
            {
                continue;
            }

            if (IsInsideBackup(spriteRenderer.transform) && !includeInactive)
            {
                continue;
            }

            if (ShouldConvertSpriteRenderer(spriteRenderer))
            {
                sprites.Add(spriteRenderer);
            }
        }

        return sprites;
    }

    private static void MergeMissingSprites(List<SpriteRenderer> target, List<SpriteRenderer> source)
    {
        for (int i = 0; i < source.Count; i++)
        {
            if (source[i] != null && !target.Contains(source[i]))
            {
                target.Add(source[i]);
            }
        }
    }

    private static bool ShouldConvertSpriteRenderer(SpriteRenderer spriteRenderer)
    {
        string objectName = spriteRenderer.name;
        if (objectName.StartsWith("ReferencePanel"))
        {
            return false;
        }

        if (HasScriptComponent(spriteRenderer.gameObject))
        {
            return false;
        }

        return IsSolidTerrainSpriteName(objectName) || IsDecorationSpriteName(objectName);
    }

    private static bool IsSolidTerrainSpriteName(string objectName)
    {
        return objectName.StartsWith("Platform") || objectName.Contains("Island");
    }

    private static bool IsDecorationSpriteName(string objectName)
    {
        string lowerName = objectName.ToLowerInvariant();
        return lowerName.Contains("waterfall")
            || lowerName.Contains("grass")
            || lowerName.Contains("tree")
            || lowerName.Contains("stump")
            || lowerName.Contains("sign")
            || lowerName.Contains("mushroom")
            || lowerName.Contains("crystal")
            || lowerName.Contains("balloon");
    }

    private static bool HasScriptComponent(GameObject gameObject)
    {
        MonoBehaviour[] scripts = gameObject.GetComponents<MonoBehaviour>();
        for (int i = 0; i < scripts.Length; i++)
        {
            if (scripts[i] != null)
            {
                return true;
            }
        }

        return false;
    }

    private static Grid GetOrCreateGrid(Transform platformRoot)
    {
        Transform gridTransform = platformRoot.Find(GridName);
        if (gridTransform != null)
        {
            Grid grid = gridTransform.GetComponent<Grid>();
            if (grid == null)
            {
                grid = gridTransform.gameObject.AddComponent<Grid>();
            }

            grid.cellSize = new Vector3(CellSize, CellSize, 1f);
            return grid;
        }

        GameObject gridObject = new GameObject(GridName);
        gridObject.transform.SetParent(platformRoot, false);
        Grid newGrid = gridObject.AddComponent<Grid>();
        newGrid.cellSize = new Vector3(CellSize, CellSize, 1f);
        return newGrid;
    }

    private static Tilemap GetOrCreateTilemap(Transform parent, string tilemapName, bool useCollider, int sortingOrder)
    {
        Transform existing = parent.Find(tilemapName);
        GameObject tilemapObject = existing != null ? existing.gameObject : new GameObject(tilemapName);
        tilemapObject.transform.SetParent(parent, false);
        tilemapObject.transform.localPosition = Vector3.zero;
        tilemapObject.transform.localRotation = Quaternion.identity;
        tilemapObject.transform.localScale = Vector3.one;

        Tilemap tilemap = tilemapObject.GetComponent<Tilemap>();
        if (tilemap == null)
        {
            tilemap = tilemapObject.AddComponent<Tilemap>();
        }

        TilemapRenderer renderer = tilemapObject.GetComponent<TilemapRenderer>();
        if (renderer == null)
        {
            renderer = tilemapObject.AddComponent<TilemapRenderer>();
        }

        renderer.mode = TilemapRenderer.Mode.Individual;
        renderer.sortingOrder = sortingOrder;

        if (useCollider)
        {
            TilemapCollider2D tilemapCollider = tilemapObject.GetComponent<TilemapCollider2D>();
            if (tilemapCollider == null)
            {
                tilemapCollider = tilemapObject.AddComponent<TilemapCollider2D>();
            }

            tilemapCollider.usedByComposite = true;

            CompositeCollider2D compositeCollider = tilemapObject.GetComponent<CompositeCollider2D>();
            if (compositeCollider == null)
            {
                compositeCollider = tilemapObject.AddComponent<CompositeCollider2D>();
            }

            Rigidbody2D rigidbody2D = tilemapObject.GetComponent<Rigidbody2D>();
            if (rigidbody2D == null)
            {
                rigidbody2D = tilemapObject.AddComponent<Rigidbody2D>();
            }

            rigidbody2D.bodyType = RigidbodyType2D.Static;
            rigidbody2D.simulated = true;
            rigidbody2D.gravityScale = 0f;
            compositeCollider.geometryType = CompositeCollider2D.GeometryType.Polygons;
        }

        return tilemap;
    }

    private static Transform GetOrCreateBackupRoot(Transform platformRoot)
    {
        Transform existing = platformRoot.Find(BackupName);
        if (existing != null)
        {
            return existing;
        }

        GameObject backupObject = new GameObject(BackupName);
        backupObject.SetActive(false);
        backupObject.transform.SetParent(platformRoot, false);
        return backupObject.transform;
    }

    private static bool IsInsideGeneratedTilemap(Transform transform)
    {
        while (transform != null)
        {
            if (transform.name == TerrainTilemapName || transform.name == DecorationTilemapName)
            {
                return true;
            }

            transform = transform.parent;
        }

        return false;
    }

    private static bool IsInsideBackup(Transform transform)
    {
        while (transform != null)
        {
            if (transform.name == BackupName)
            {
                return true;
            }

            transform = transform.parent;
        }

        return false;
    }

    private static Tile GetOrCreateTile(Sprite sprite)
    {
        string sourcePath = AssetDatabase.GetAssetPath(sprite);
        string safeName = Path.GetFileNameWithoutExtension(string.IsNullOrEmpty(sourcePath) ? sprite.name : sourcePath);
        string tilePath = Path.Combine(TileFolder, $"{safeName}.asset").Replace('\\', '/');

        Tile tile = AssetDatabase.LoadAssetAtPath<Tile>(tilePath);
        if (tile == null)
        {
            tile = ScriptableObject.CreateInstance<Tile>();
            AssetDatabase.CreateAsset(tile, tilePath);
        }

        tile.sprite = sprite;
        tile.name = sprite.name;
        EditorUtility.SetDirty(tile);
        return tile;
    }

    private static Vector3Int FindNearestEmptyCell(Vector3Int cell, HashSet<Vector3Int> usedCells)
    {
        if (!usedCells.Contains(cell))
        {
            return cell;
        }

        for (int radius = 1; radius < 20; radius++)
        {
            for (int x = -radius; x <= radius; x++)
            {
                for (int y = -radius; y <= radius; y++)
                {
                    Vector3Int candidate = new Vector3Int(cell.x + x, cell.y + y, cell.z);
                    if (!usedCells.Contains(candidate))
                    {
                        return candidate;
                    }
                }
            }
        }

        return cell;
    }

    private static void EnsureTileFolderExists()
    {
        if (!AssetDatabase.IsValidFolder("Assets/Tiles"))
        {
            AssetDatabase.CreateFolder("Assets", "Tiles");
        }

        if (!AssetDatabase.IsValidFolder(TileFolder))
        {
            AssetDatabase.CreateFolder("Assets/Tiles", "AutoGeneratedTerrain");
        }
    }
}
#endif
